baseURL = 'https://zishan-shao.github.io/'
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Zishan Shao"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = false
relativeURLs = true
canonifyURLs = true

[frontmatter]
lastmod = ["lastmod", ":fileModTime", ":default"]


# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Zishan Shao"
author = "Zishan Shao"
copyright = "2023"
description = "Undergraduate Researcher at Wake Forest University\nshaoz20@wfu.edu\n "
profilePicture = "../me.jpeg" # "../raiden.png"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = true

indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"
singleDateFormat = "Mon, Jan 2, 2006"


[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/zishan-shao-ab2ba926b/"


[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/Zishan-Shao"


#[[params.socialIcons]]
#icon = "ai ai-google-scholar"
#title = "GoogleScholar"
#url = "https://scholar.google.com/citations?user=Ao-FJHwAAAAJ&hl=en"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "https://mail.google.com/"

[[params.socialIcons]]
icon = "ai ai-cv"
title = "CV"
url = "../bruce_cv.pdf"

#[[params.socialIcons]]
#icon = "ai ai-orcid"
#title = "ORCID"
#url = "https://orcid.org/0000-0002-8251-9150"

[markup.goldmark.renderer]
unsafe= true

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 200
  identifier = "about"
  url = "/about/"

  #[[menu.main]]
  #name = "Teaching"
  #weight = 300
  #identifier = "Teaching"
  #url = "/teaching/"

  [[menu.main]]
  name = "Research"
  weight = 300
  identifier = "research"
  url = "/research/"

  [[menu.main]]
  name = "Hobbys"
  weight = 400
  identifier = "hobby"
  url = "/hobby/"

  #[[menu.main]]
  #name = "Publications"
  #weight = 500
  #identifier = "publications"
  #url = "/publications/"



